"""
Combined Export Module

Exports vocabulary, semantic search results, and summary in a single document.

This creates a unified report with:
1. Summary (if available)
2. Names & Vocabulary table
3. Semantic Search Results section

Supports Word (.docx), PDF, and TXT formats.
"""

import logging

from src.core.export.base import DocumentBuilder
from src.core.export.semantic_exporter import export_semantic_results
from src.core.export.vocab_exporter import export_vocabulary

logger = logging.getLogger(__name__)


def export_combined(
    vocab_data: list[dict],
    semantic_results: list,
    builder: DocumentBuilder,
    include_vocab_details: bool = False,
    title: str = "Document Analysis Report",
    summary_text: str = "",
) -> None:
    """
    Export vocabulary, semantic search results, and summary to a single document.

    Args:
        vocab_data: List of vocabulary dicts
        semantic_results: List of SemanticResult objects
        builder: DocumentBuilder instance (Word or PDF)
        include_vocab_details: Include algorithm columns in vocabulary table
        title: Document title
        summary_text: Summary text to include (empty string to skip)
    """
    logger.debug(
        "Creating combined report: %d terms, %d search results, summary=%s",
        len(vocab_data),
        len(semantic_results),
        bool(summary_text),
    )

    # Document title
    builder.add_heading(title, level=1)
    builder.add_paragraph("")  # Spacer

    # Section 1: Summary
    if summary_text:
        builder.add_heading("Summary", level=2)
        builder.add_paragraph(summary_text)
        builder.add_paragraph("")  # Spacer

    # Section 2: Vocabulary
    if vocab_data:
        export_vocabulary(vocab_data, builder, include_vocab_details)
        builder.add_paragraph("")  # Spacer after table

    # Section 3: Search Results
    if semantic_results:
        export_semantic_results(semantic_results, builder)

    # Footer note
    builder.add_paragraph("")
    builder.add_paragraph("Generated by CasePrepd")

    logger.debug("Combined report generation complete")


def export_combined_txt(
    vocab_data: list[dict],
    semantic_results: list,
    summary_text: str,
    file_path: str,
) -> bool:
    """
    Export vocabulary, semantic search results, and summary to a plain text file.

    Args:
        vocab_data: List of vocabulary dicts
        semantic_results: List of SemanticResult objects
        summary_text: Summary text string
        file_path: Output file path (.txt)

    Returns:
        True if successful
    """
    from pathlib import Path

    from src.core.export.base import format_export_timestamp
    from src.core.vocab_schema import VF

    sections = [f"Case Report\nGenerated {format_export_timestamp()}\n"]

    if vocab_data:
        sections.append(_build_vocab_txt(vocab_data, VF))
    if semantic_results:
        sections.append(_build_search_txt(semantic_results))
    if summary_text and summary_text.strip():
        sections.append(_build_summary_txt(summary_text))

    sections.append("Generated by CasePrepd")
    content = "\n".join(sections)
    Path(file_path).write_text(content, encoding="utf-8")
    return True


def _build_vocab_txt(vocab_data: list[dict], VF) -> str:
    """Build the vocabulary section for TXT export."""
    lines = [_section_divider("VOCABULARY")]
    for v in vocab_data:
        term = v.get(VF.TERM, "")
        score = v.get(VF.QUALITY_SCORE, "")
        is_person = v.get(VF.IS_PERSON, "")
        label = " [Person]" if is_person == VF.YES else ""
        lines.append(f"  {term} (score: {score}){label}")
    lines.append("")
    return "\n".join(lines)


def _build_search_txt(semantic_results: list) -> str:
    """Build the search results section for TXT export."""
    lines = [_section_divider("SEARCH RESULTS")]
    for i, result in enumerate(semantic_results, 1):
        lines.append(f"Q{i}: {result.question}")
        if result.citation:
            lines.append(f"  Citation: {result.citation}")
        if result.source_summary:
            lines.append(f"  Source: {result.source_summary}")
        relevance_pct = int(result.relevance * 100)
        lines.append(f"  Relevance: {relevance_pct}%")
        lines.append("")
    return "\n".join(lines)


def _build_summary_txt(summary_text: str) -> str:
    """Build the key excerpts section for TXT export."""
    lines = [_section_divider("KEY EXCERPTS"), summary_text.strip(), ""]
    return "\n".join(lines)


def _section_divider(title: str) -> str:
    """Create a section divider line for TXT exports."""
    return f"\n{'=' * 60}\n  {title}\n{'=' * 60}\n"
